version: '3.8'

services:
  # Servicio de Base de Datos PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: biblioteca_postgres
    restart: always
    environment:
      - POSTGRES_DB=biblioteca_db      # Nombre de la BD
      - POSTGRES_USER=admin            # Usuario
      - POSTGRES_PASSWORD=admin123     # Contraseña
    ports:
      - "5432:5432"                    # Puerto externo:interno
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
    networks:
      - biblioteca-net

  # Servicio de pgAdmin (Interfaz gráfica para la BD)
  pgadmin:
    image: dpage/pgadmin4
    container_name: biblioteca_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - biblioteca-net

volumes:
  postgres_data:

networks:
  biblioteca-net:
    driver: bridge